Title =  "ianhuang筆記"
LanguageCode = "zh-TW"
BaseUrl = "https://iankingh.github.io/"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
pygmentsCodefences = false
pygmentsCodefencesGuessSyntax = false
DefaultContentLanguage = "zh"
disqusShortname = "https-iankingh-github-io"


[Params]
  Introduce = "Programmer & Architect"
  Description = "筆記 | 軟體 | 架構 | Java "
  Keywords =  "程式師,架構師,個人,筆記,技術"
  Subtitle = "總有一天，你的日積月累，會變成他人的望塵莫及"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  #BaiduStatsId = "0b07433b4ab8d587dae7d34e71973839"
  #QQStatsId = "58416275"
  RevolverMapId = "5b4f2ucxar6"
  Fancybox = true

[Author]
  Name = "ianhuang"

[Params.Share]
  #DuoShuo = "lanlingzi"
  Baidu = true

[[Menu.Main]]
  Name = "首頁"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "技術"
  Pre = "code"
  URL = "/categories/技術/"
  Weight = 2
[[Menu.Main]]
  Name = "筆記"
  Pre = "book"
  URL = "/categories/筆記/"
  Weight = 4
[[Menu.Main]]
  Name = "歸檔"
  Pre = "archive"
  URL = "/post/"
  Weight = 5
[[Menu.Main]]
  Name = "關於"
  Pre = "user"
  URL = "/about/"
  Weight = 6

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/iankingh"

